name: Post welcome comment by Jesus Lopez
on:
  pull_request:
    types: [opened]
permissions:
  pull-requests: write
jobs:
 build:
   name: post welcome comment by Jesus Lopez
   runs-on: ubuntu-latest
   steps:
      - run: gh pr comment $PR_URL --body "Welcome to my cloned repository!"
        env:
          GITHuB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          PR_URL: ${{github.event.pull_request.html_url}}
